dialogue_monitor:
  api:
    api_key: sk-b36ed8eaabcf464db3dab96707965f85
    base_url: https://api.deepseek.com/v1
  max_tokens: 10
  model: deepseek-v4-pro
  temperature: 0.1
judger:
  api:
    api_key: sk-b36ed8eaabcf464db3dab96707965f85
    base_url: https://api.deepseek.com/v1
  model: deepseek-v4-pro
  temperature: 0.1
  top_p: 1.0
virtual_doctor:
  api:
    api_key: sk-e3cf7b36bd3c433a9f4757eab86cae25
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: qwen3-8b
  temperature: 0.8
  top_p: 0.9
virtual_patient:
  api:
    api_key: sk-b36ed8eaabcf464db3dab96707965f85
    base_url: https://api.deepseek.com/v1
  model: deepseek-v4-pro
  reasoning_effort: high
  temperature: 0.8
  thinking_enabled: true
  top_p: 0.9
